### model
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
#resize_token_embeddings: false

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_offload_h100_config.json
flash_attn: fa2

### dataset
dataset: limo
cutoff_len: 16384
overwrite_cache: true
preprocessing_num_workers: 16
template: llama3
packing: true 

### output
output_dir: saves/llama3.1-8b/full
logging_steps: 1
save_strategy: steps
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 5.0e-6
num_train_epochs: 15
lr_scheduler_type: cosine
warmup_ratio: 0.0
bf16: true
tf32: true
ddp_timeout: 180000000
report_to: neptune